#1 firefox align
UniaoInstavel/uniaoinstavel.github.io pull request #2
Opened 2020-08-21 23:28 UTC by juliatotta

Fixes #1

2020-08-22 00:04 UTC, csestelo requested changes
Testei em vários devices e funcionou bem demais, vai ter que mudar seu sobrenome pra responsividade kkkk. Só deixei um comentário pra vc revisar.

2020-08-22 00:04 UTC, csestelo commented on styles.css
> +@import url('https://fonts.googleapis.com/css2?family=Baloo+Tamma+2&display=swap');
Curti, não sabia que importava fonte assim. =D

2020-08-22 00:04 UTC, csestelo commented on styles.css
> +    font-family: 'Baloo Tamma 2', cursive;
Curti a escolha de fonte principal, bonita e simples. Sobre as fontes 'seguras', sugiro de continuarmos com as anteriores. 
1 - pq `cursive` é muito diferente da principal, então é perceptível a mudança de estilo enquanto a fonte principal está sendo baixada.
2 - esse segundo argumento é completamente arbitrário, só por motivos de gosto mesmo haha. Acho `cursive` meio breguinha.

```suggestion
    font-family: 'Baloo Tamma 2', Helvetica,sans-serif;
```

2020-08-23 20:14 UTC, juliatotta commented on styles.css
> +    font-family: 'Baloo Tamma 2', cursive;
Concordo contigo que a cursive não e a melhor opção, mas eu não me liguei porque importei do Google Fonts e a font family veio com esse padrão. Depois que eu vi seu comentário que fui reparar nisso, rs.

2020-08-23 20:20 UTC, juliatotta commented on styles.css
> +    font-family: 'Baloo Tamma 2', cursive;
Sugestão aplicada :D

2020-08-23 20:42 UTC, merged